language: node_js
node_js:
 - "11.9.0"
branches:
 only:
 - master
before_script:
 - npm install
script:
 - npm run deploy
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www
